version: '3.8'

services:
  # mongo hosted: mongodb atlas

  blogs-backend:
    image: blogs-backend
    build:
      context: ./blogs-backend/ 
      dockerfile: Dockerfile
    volumes:
      - ./blogs-backend:/usr/src/app
    ports:
      - 3003:3003
    env_file:
      - ./blogs-backend/.env
    environment: 
      - WATCHPACK_POLLING=true
    container_name: blogs-backend-prod

  blogs-frontend:
    image: blogs-frontend
    build:
      context: ./blogs-frontend/ 
      dockerfile: Dockerfile 
    volumes:
      - ./blogs-frontend:/usr/src/app # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
    ports:
      - 3000:3000
    container_name: blogs-frontend-prod # 

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - blogs-frontend
      - blogs-backend